server:
  port: 8000
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: mutual_subscribers_bot
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  flyway:
#    url: ${spring.datasource.url}
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#    driver-class-name: ${spring.datasource.driver-class-name}
#    enabled: true
#    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        highlight_sql: true
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: update # validate

application:
  telegram:
    token: ${TELEGRAM_TOKEN}
    name: ${TELEGRAM_NAME}
  multi-threading:
    update-consumer:
      core-pool-size: ${MULTI_CORE_POOL_SIZE:10}
      max-pool-size: ${MULTI_MAX_POOL_SIZE:50}
      keep-alive-time: ${MULTI_KEEP_ALIVE:60}
      queue-capacity: ${MULTI_QUEUE_CAPACITY:200}